service: fastapi-sls-tester

package:
  individually: true
  patterns:
    - '!**'
    - 'app/**'
    - '!app/**/__pycache__'
    - '!app/**/*.pyc'

useDotenv: true

provider:
  name: aws  
  region: "eu-west-1"
  stage: ${opt:stage, "dev"}
  runtime: python3.11

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true
    layer:
      name: ${self:service}-${self:provider.stage}-requirements
      description: "Requirements layer for ${self:service}-${self:provider.stage}"
      compatibleRuntimes:
        - python3.11

functions:
  app:
    handler: app.main.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          method: get
          path: /
      - http:
          method: any
          path: /{proxy+}